version: 2
defaults: &defaults
    docker:
      - image:  cimg/python:3.11.0-browsers       
install_dependency: &install_dependency
          name: Installation of build and deployment dependencies.
          command: |
            sudo apt update
            sudo apt install jq
            sudo apt install python3-pip
            sudo pip3 install awscli --upgrade
            sudo pip3 install docker-compose
install_deploysuite: &install_deploysuite
          name: Installation of install_deploysuite.
          command: |
            git clone --branch v1.4.15 https://github.com/topcoder-platform/tc-deploy-scripts ../buildscript
            cp ./../buildscript/master_deploy.sh .
            cp ./../buildscript/master_deploy.sh .
            cp ./../buildscript/buildenv.sh .
            cp ./../buildscript/awsconfiguration.sh .

restore_cache_settings_for_build: &restore_cache_settings_for_build
  key: docker-node-modules-{{ checksum "package-lock.json" }}

save_cache_settings: &save_cache_settings
  key: docker-node-modules-{{ checksum "package-lock.json" }}
  paths:
    - node_modules

run_build: &run_build
          name: Building images
          command: ./build.sh

build_steps: &build_steps
      - checkout
      - setup_remote_docker
      - run: *install_dependency
      - run: *install_deploysuite
      - restore_cache: *restore_cache_settings_for_build
      - run: *run_build
      - save_cache: *save_cache_settings
      - deploy:
          name: Running MasterScript.
          command: |
            ./awsconfiguration.sh ${DEPLOY_ENV}
            source awsenvconf
            ./buildenv.sh -e ${DEPLOY_ENV} -b ${LOGICAL_ENV}-${APP_NAME}-deployvar
            source buildenvvar
            ./master_deploy.sh -d ECS -e ${DEPLOY_ENV} -t latest -s ${LOGICAL_ENV}-global-appvar,${LOGICAL_ENV}-global-informix-appvar,${LOGICAL_ENV}-${APP_NAME}-appvar -i terms-service

jobs:
  # Build & Deploy against development backend
  "build-dev":
    <<: *defaults
    environment:
      DEPLOY_ENV: "DEV"
      LOGICAL_ENV: "dev"
      APP_NAME: "terms-service"
    steps: *build_steps
  # Build & Deploy against development backend
  "build-qa":
    <<: *defaults
    environment:
      DEPLOY_ENV: "QA"
      LOGICAL_ENV: "qa"
      APP_NAME: "terms-service"
    steps: *build_steps    
  # Build & Deploy against production backend
  "build-prod":
    <<: *defaults
    environment:
      DEPLOY_ENV: "PROD"
      LOGICAL_ENV: "prod"
      APP_NAME: "terms-service"
    steps: *build_steps
workflows:
  version: 2
  build:
    jobs:
      # Development builds are executed on "develop" branch only.
      - "build-dev":
          context : org-global
          filters:
            branches:
              only:
                - dev
      - "build-qa":
          context : org-global
          filters:
            branches:
              only:
                - qa                
      - "build-prod":
          context : org-global
          filters:
            branches:
              only:
                - master
